name: Docker Image CI for Simple Http Proxy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASS: ${{secrets.DOCKER_PASS}}
      run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
    - name: Build the Docker image
      run: docker build . --file http_proxy.Dockerfile --tag tyronesch/simple_http_proxy:0.1
    - name: list images 
      run: docker image ls 
    - name: run images 
      run: docker run  tyronesch/simple_http_proxy:0.1
    - name: Docker Push #tyronesch/python_hello_world:tagname
      run: docker push tyronesch/simple_http_proxy:0.1
